version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=3321
      - POSTGRES_DB=main
    ports:
      - "5432:5432"
    networks:
      - node_rest

  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=3321
    ports:
      - "27017:27017"
    networks:
      - node_rest

networks:
  node_rest:
    driver: bridge
    